apiVersion: v1
kind: Service
metadata:
  name: {{ include "todos.fullname" . }}-mongodb
  labels:
    {{- include "todos.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "todos.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
