apiVersion: v1
kind: Service
metadata:
  name: {{ include "todos.fullname" . }}-server
  labels:
    {{- include "todos.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "todos.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
