apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todos.fullname" . }}-server
  labels:
    {{- include "todos.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      {{- include "todos.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        {{- include "todos.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.repository }}/{{ .Values.server.image }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
          - secretRef:
              name: ibm-code-challenge
