apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todos.fullname" . }}-ui
  labels:
    {{- include "todos.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      {{- include "todos.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui
  template:
    metadata:
      labels:
        {{- include "todos.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ui
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.repository }}/{{ .Values.ui.image }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
