apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: {{ include "todos.fullname" . }}-ui
 annotations:
   kubernetes.io/ingress.class: "public-iks-k8s-nginx"
   nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
 tls:
 - hosts:
   - {{ .Values.domain }}
   secretName: jrdemo-c4a24be17d2b0bfc980895fd31267ec3-0000
 rules:
 - host: {{ .Values.domain }}
   http:
     paths:
     - path: /ibm-code-challenge/(.*)
       pathType: Prefix
       backend:
        service:
          name: {{ include "todos.fullname" . }}-ui
          port:
            number: 80
